### ISSUE TITLE
Problem with images in room

### ISSUE THREAD

**Issue by gep13** [Odonno/modern-gitter-winjs#37]
I noticed an issue in a couple rooms when using the application this morning.

When I entered each room, there were images posted into some of the messages, and the text from other messages were over the top of the images.  I was hoping to get a screenshot of the problem, but when I got to my computer and opened the rooms again, the images are appearing correctly.

If it happens again, I will update this issue with a screenshot.

**Comment by Odonno** [comment]
I think I had the same and maybe caused by the same bug that happens in #35.

Once the UI is refreshed (ex: scroll), the message height is recalculated based on image height. There is also another bug if the image is too big (it goes beyond screen width).

![capture](https://cloud.githubusercontent.com/assets/6053067/12697295/33d371b2-c780-11e5-89af-1cc6d05b494f.PNG)

**Comment by Odonno** [comment]
I just got the bug you describe right now on my other device.

![capture](https://cloud.githubusercontent.com/assets/6053067/12697313/8caf105c-c780-11e5-8efc-3af410f4d59c.PNG)

Indeed, refreshing the UI should fix the bug.

**Comment by gep13** [comment]
Yip, that last screenshot is exactly what I was seeing on my phone as well.

**Comment by Odonno** [comment]
@gep13 The new version (2.3.6) should have fixed this bug.
